#!/bin/sh
# -*- sh-basic-offset:4; indent-tabs-mode:nil -*- vi: set sw=4 et:

# MIT License
#
# Copyright (c) 2016 Earl Chew

set -eu

[ -z "${0##*/*}" ] || exec "$PWD/$0" "$@"

. "${0%/*}"/cloudflare-cli.sh

usage()
{
    {
        print "Usage: $0 email apitoken zone type host [ = [ content ] ]"
        print "Examples:"
        print "  Read A record for www.company.com"
        print "    $0 user@company.com a31c3d company.com A www"
        print "  Write A record for company.com"
        print "    $0 user@company.com a31c3d company.com A @ = 10.4.12.3"
        print "  Delete TXT record for test.company.com"
        print "    $0 user@company.com a31c3d company.com TXT test ="
    } >&2
    exit 1
}

[ $# -ge 5 -a $# -le 7 ] &&
{ [ $# -lt 6 ] || [ x"$6" = x"=" ] ; } || usage

EMAIL=$1    ; shift
APITOKEN=$1 ; shift
ZONE=$1     ; shift
TYPE=$1     ; shift
HOST=$1     ; shift

if [ $# -eq 0 ] ; then
    cloudflareRead "$EMAIL" "$APITOKEN" "$ZONE" "$TYPE" "$HOST" ||
        fail "Unable to read $HOST $TYPE record in zone $ZONE"
elif [ $# -eq 2 ] ; then
    cloudflareWrite "$EMAIL" "$APITOKEN" "$ZONE" "$TYPE" "$HOST" "$2" ||
        fail "Unable to write $HOST $TYPE record in zone $ZONE"
else
    cloudflareDelete "$EMAIL" "$APITOKEN" "$ZONE" "$TYPE" "$HOST" ||
        fail "Unable to delete $HOST $TYPE record in zone $ZONE"
fi

exit $?
